<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-FRBHI3MI" failures="1" tests="1" name="Test" time="12.587" errors="0" timestamp="2023-10-12T19:24:09 IST">
  <testcase classname="com.LoginTest.VerifyLoginTestNayan" name="TC_LoginTest_1_VerifyLoginTestWithValidCrdentials" time="1.345">
    <failure type="java.lang.AssertionError" message="expected [Logged In Successfully] but found [Test Login | Practice Test Automation]">
      <![CDATA[java.lang.AssertionError: expected [Logged In Successfully] but found [Test Login | Practice Test Automation]
at com.LoginTest.VerifyLoginTestNayan.TC_LoginTest_1_VerifyLoginTestWithValidCrdentials(VerifyLoginTestNayan.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC_LoginTest_1_VerifyLoginTestWithValidCrdentials -->
</testsuite> <!-- Test -->
